// Numerical rules adapted from SRD 5.1; see NOTICE.md.
export const RULESET = "srd-5.1-2014";
export const ABILITIES = ["str", "dex", "con", "int", "wis", "cha"];
export const SKILLS = {
  acrobatics: "dex",
  animal_handling: "wis",
  arcana: "int",
  athletics: "str",
  deception: "cha",
  history: "int",
  insight: "wis",
  intimidation: "cha",
  investigation: "int",
  medicine: "wis",
  nature: "int",
  perception: "wis",
  performance: "cha",
  persuasion: "cha",
  religion: "int",
  sleight_of_hand: "dex",
  stealth: "dex",
  survival: "wis",
};
export const CONDITIONS = [
  "blinded",
  "charmed",
  "deafened",
  "frightened",
  "grappled",
  "incapacitated",
  "invisible",
  "paralyzed",
  "petrified",
  "poisoned",
  "prone",
  "restrained",
  "stunned",
  "unconscious",
];
export const DAMAGE_TYPES = [
  "acid",
  "bludgeoning",
  "cold",
  "fire",
  "force",
  "lightning",
  "necrotic",
  "piercing",
  "poison",
  "psychic",
  "radiant",
  "slashing",
  "thunder",
];
export const CLASSES = {
  barbarian: { hitDie: 12, saves: ["str", "con"] },
  bard: { hitDie: 8, saves: ["dex", "cha"], casting: "cha", slots: "full" },
  cleric: { hitDie: 8, saves: ["wis", "cha"], casting: "wis", slots: "full" },
  druid: { hitDie: 8, saves: ["int", "wis"], casting: "wis", slots: "full" },
  fighter: { hitDie: 10, saves: ["str", "con"] },
  monk: { hitDie: 8, saves: ["str", "dex"] },
  paladin: { hitDie: 10, saves: ["wis", "cha"], casting: "cha", slots: "half" },
  ranger: { hitDie: 10, saves: ["str", "dex"], casting: "wis", slots: "half" },
  rogue: { hitDie: 8, saves: ["dex", "int"] },
  sorcerer: { hitDie: 6, saves: ["con", "cha"], casting: "cha", slots: "full" },
  warlock: { hitDie: 8, saves: ["wis", "cha"], casting: "cha", slots: "pact" },
  wizard: { hitDie: 6, saves: ["int", "wis"], casting: "int", slots: "full" },
};
export const FULL_SLOTS = [
  [],
  [2],
  [3],
  [4, 2],
  [4, 3],
  [4, 3, 2],
  [4, 3, 3],
  [4, 3, 3, 1],
  [4, 3, 3, 2],
  [4, 3, 3, 3, 1],
  [4, 3, 3, 3, 2],
  [4, 3, 3, 3, 2, 1],
  [4, 3, 3, 3, 2, 1],
  [4, 3, 3, 3, 2, 1, 1],
  [4, 3, 3, 3, 2, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 2, 1, 1, 1, 1],
  [4, 3, 3, 3, 3, 1, 1, 1, 1],
  [4, 3, 3, 3, 3, 2, 1, 1, 1],
  [4, 3, 3, 3, 3, 2, 2, 1, 1],
];
export const XP = [
  0, 300, 900, 2700, 6500, 14000, 23000, 34000, 48000, 64000, 85000, 100000,
  120000, 140000, 165000, 195000, 225000, 265000, 305000, 355000,
];
export const WEAPONS = {
  club: {
    dice: "1d4",
    type: "bludgeoning",
    category: "simple",
    melee: true,
    reach: 5,
  },
  dagger: {
    dice: "1d4",
    type: "piercing",
    category: "simple",
    melee: true,
    finesse: true,
    reach: 5,
    range: [20, 60],
  },
  quarterstaff: {
    dice: "1d6",
    twoHandDice: "1d8",
    type: "bludgeoning",
    category: "simple",
    melee: true,
    reach: 5,
  },
  shortsword: {
    dice: "1d6",
    type: "piercing",
    category: "martial",
    melee: true,
    finesse: true,
    reach: 5,
  },
  longsword: {
    dice: "1d8",
    twoHandDice: "1d10",
    type: "slashing",
    category: "martial",
    melee: true,
    reach: 5,
  },
  greatsword: {
    dice: "2d6",
    type: "slashing",
    category: "martial",
    melee: true,
    twoHanded: true,
    reach: 5,
  },
  rapier: {
    dice: "1d8",
    type: "piercing",
    category: "martial",
    melee: true,
    finesse: true,
    reach: 5,
  },
  shortbow: {
    dice: "1d6",
    type: "piercing",
    category: "simple",
    melee: false,
    twoHanded: true,
    range: [80, 320],
    ammo: "arrow",
  },
  longbow: {
    dice: "1d8",
    type: "piercing",
    category: "martial",
    melee: false,
    twoHanded: true,
    range: [150, 600],
    ammo: "arrow",
  },
  light_crossbow: {
    dice: "1d8",
    type: "piercing",
    category: "simple",
    melee: false,
    twoHanded: true,
    range: [80, 320],
    ammo: "bolt",
    loading: true,
  },
};
export const ARMOR = {
  none: { base: 10, dex: true },
  leather: { base: 11, dex: true },
  studded_leather: { base: 12, dex: true },
  hide: { base: 12, dex: 2 },
  chain_shirt: { base: 13, dex: 2 },
  scale_mail: { base: 14, dex: 2, stealthDisadvantage: true },
  breastplate: { base: 14, dex: 2 },
  half_plate: { base: 15, dex: 2, stealthDisadvantage: true },
  ring_mail: { base: 14, dex: false, stealthDisadvantage: true },
  chain_mail: { base: 16, dex: false, str: 13, stealthDisadvantage: true },
  splint: { base: 17, dex: false, str: 15, stealthDisadvantage: true },
  plate: { base: 18, dex: false, str: 15, stealthDisadvantage: true },
};
export const SPELLS = {
  fire_bolt: {
    level: 0,
    classes: ["sorcerer", "wizard"],
    range: 120,
    action: "action",
    kind: "attack",
    dice: "1d10",
    damageType: "fire",
    components: ["V", "S"],
  },
  sacred_flame: {
    level: 0,
    classes: ["cleric"],
    range: 60,
    action: "action",
    kind: "save",
    save: "dex",
    dice: "1d8",
    damageType: "radiant",
    components: ["V", "S"],
  },
  cure_wounds: {
    level: 1,
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    range: 5,
    action: "action",
    kind: "heal",
    dice: "1d8",
    components: ["V", "S"],
  },
  healing_word: {
    level: 1,
    classes: ["bard", "cleric", "druid"],
    range: 60,
    action: "bonus",
    kind: "heal",
    dice: "1d4",
    components: ["V", "S"],
  },
  magic_missile: {
    level: 1,
    classes: ["sorcerer", "wizard"],
    range: 120,
    action: "action",
    kind: "missiles",
    components: ["V", "S"],
  },
  bless: {
    level: 1,
    classes: ["cleric", "paladin"],
    range: 30,
    action: "action",
    kind: "bless",
    concentration: true,
    duration: 60,
    components: ["V", "S", "M"],
  },
  mage_armor: {
    level: 1,
    classes: ["sorcerer", "wizard"],
    range: 5,
    action: "action",
    kind: "armor",
    duration: 28800,
    components: ["V", "S", "M"],
  },
  fireball: {
    level: 3,
    classes: ["sorcerer", "wizard"],
    range: 150,
    action: "action",
    kind: "area",
    save: "dex",
    dice: "8d6",
    damageType: "fire",
    radius: 20,
    components: ["V", "S", "M"],
  },
};
export const MONSTERS = {
  goblin: {
    name: "Goblin",
    type: "humanoid",
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    maxHp: 7,
    ac: 15,
    speed: 30,
    cr: "1/4",
    xp: 50,
    attacks: {
      scimitar: { bonus: 4, dice: "1d6+2", type: "slashing", reach: 5 },
      shortbow: { bonus: 4, dice: "1d6+2", type: "piercing", range: [80, 320] },
    },
    manualFeatures: ["Nimble Escape"],
  },
  skeleton: {
    name: "Skeleton",
    type: "undead",
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    maxHp: 13,
    ac: 13,
    speed: 30,
    cr: "1/4",
    xp: 50,
    immunities: ["poison"],
    vulnerabilities: ["bludgeoning"],
    conditionImmunities: ["poisoned"],
    attacks: {
      shortsword: { bonus: 4, dice: "1d6+2", type: "piercing", reach: 5 },
      shortbow: { bonus: 4, dice: "1d6+2", type: "piercing", range: [80, 320] },
    },
    manualFeatures: [
      "Exhaustion immunity; no breathing, eating, drinking, or sleep",
    ],
  },
  ogre: {
    name: "Ogre",
    type: "giant",
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    maxHp: 59,
    ac: 11,
    speed: 40,
    cr: "2",
    xp: 450,
    attacks: {
      greatclub: { bonus: 6, dice: "2d8+4", type: "bludgeoning", reach: 5 },
      javelin: {
        bonus: 6,
        dice: "2d6+4",
        type: "piercing",
        reach: 5,
        range: [30, 120],
      },
    },
    manualFeatures: [],
  },
  bandit: {
    name: "Bandit",
    type: "humanoid",
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    maxHp: 11,
    ac: 12,
    speed: 30,
    cr: "1/8",
    xp: 25,
    attacks: {
      scimitar: { bonus: 3, dice: "1d6+1", type: "slashing", reach: 5 },
      light_crossbow: {
        bonus: 3,
        dice: "1d8+1",
        type: "piercing",
        range: [80, 320],
      },
    },
    manualFeatures: [],
  },
};
export function slotMaximums(className, level) {
  const kind = CLASSES[className]?.slots;
  if (kind === "pact")
    return {
      [Math.min(5, Math.ceil(level / 2))]:
        level === 1 ? 1 : level < 11 ? 2 : level < 17 ? 3 : 4,
    };
  const row =
    FULL_SLOTS[
      kind === "full"
        ? level
        : kind === "half" && level >= 2
          ? Math.ceil(level / 2)
          : 0
    ];
  return Object.fromEntries(row.map((n, i) => [i + 1, n]));
}
export const COVERAGE = {
  ruleset: RULESET,
  automated: [
    "Seed-free cryptographic dice with individual rolls",
    "Ability checks, skills, expertise, saves, advantage/disadvantage",
    "Single-class sheet chassis for all 12 SRD classes, levels 1–20; fixed-average HP and slot progression",
    "Initiative, surprise, actions, bonus actions, reactions, extra attacks, movement, dash, dodge, disengage",
    "Weapon attacks, range, ammunition, criticals, AC, typed damage, resistance, vulnerability, temporary HP",
    "Death saves, instant death, stabilization, healing, concentration",
    "8 spell effect implementations and spell-slot consumption",
    "Short/long rests, hit dice, exhaustion, time, inventory, currency, XP and explicit level advancement",
    "Persistent campaigns, scenes, journal, audit events, revisions and retry deduplication",
    "Offline search and page retrieval across the entire official SRD 5.1",
    "Optional square/axial-hex maps with pathfinding, occupancy, difficult terrain and legal movement queries",
    "Opaque full-cell obstacles block center-to-center targeting and area propagation on square/hex maps; read-only sight-line queries",
    "Scheduled round-boundary reinforcements with occupied-entry deferral",
  ],
  gmAdjudicated: [
    "Final character ability scores, race/background traits, skill and equipment eligibility, prepared/known spell limits",
    "Class/subclass features beyond core chassis and Extra Attack; feats, multiclassing, attunement",
    "Unmapped sight, partial cover (supplied per attack), lighting, hiding, social outcomes, unmapped terrain, opportunity-attack triggers",
    "Charmed/frightened source relationships; grapple contests and escape; condition sources and expiry",
    "Spell components, counterspells, readied actions, noncatalog spells and magic items",
    "Monster special traits, multiattack, legendary/lair actions; encounter balance; quest and treasure awards",
    "Food/water, rest interruptions, racial rest exceptions, travel hazards",
  ],
  boundaries: [
    "Trusted local game-master interface; no player authentication or hidden-information isolation",
    "Core transport is stdio MCP; optional local development viewer is a separate client",
    "Positions are optional 5-foot coordinates; mapped square or axial-hex geometry. Single-cell tokens, conservative occupancy. Participants must all have positions or all omit them",
    "Obstacle sight uses closed cells: edge/corner contact blocks. Area effects use direct radial lines, not around-corner propagation. Actors do not block sight; elevation and special senses are unmodeled",
    "Supply encounter_end.xp for atomic equal-share encounter XP, or use xp_award for separately adjudicated awards; never both for the same reward",
    "No 2024/5.5e mechanics; ruleset fixed per campaign",
  ],
};
