import { definitionId, namedUuid } from "./identity.js";

const BASE_STOCKPILES = [
  [
    "stable_smithy_supplies",
    "Smithy supply crates",
    "smithy_supplies",
    3,
    38,
    23,
    "cart",
  ],
  [
    "smithy_supplies",
    "Smithy working stock",
    "smithy_supplies",
    0,
    11,
    3,
    "forge",
    2,
    6,
  ],
  [
    "smithy_weapons",
    "Finished ash spears",
    "ash_spear",
    0,
    3,
    3,
    "counter",
    1,
    4,
    "smithy",
  ],
  [
    "hunting_bows",
    "Finished hunting bows",
    "shortbow",
    0,
    11,
    3,
    "forge",
    2,
    4,
  ],
  [
    "apothecary_herbs",
    "Medicinal herbs",
    "medicinal_herbs",
    3,
    36,
    3,
    "fixture",
  ],
  [
    "apothecary_remedies",
    "Healing potions",
    "healing_potion",
    0,
    27,
    3,
    "counter",
    2,
    6,
    "apothecary",
  ],
  [
    "armorer_materials",
    "Armor fittings",
    "armor_fittings",
    3,
    34,
    16,
    "fixture",
  ],
  [
    "armorer_shields",
    "Reinforced shields",
    "reinforced_shield",
    0,
    24,
    16,
    "counter",
    1,
    4,
    "armorer",
  ],
  [
    "netting_fiber",
    "Netting fiber bundles",
    "netting_fiber",
    6,
    38,
    23,
    "cart",
    4,
    12,
  ],
  [
    "fishing_nets",
    "Fishing hut net rack",
    "fishing_net",
    0,
    38,
    23,
    "cart",
    2,
    4,
  ],
  ["river_catch", "Fresh river fish", "raw_fish", 0, -1, 15, "fixture", 8, 24],
  ["inn_fish", "Inn fish pantry", "raw_fish", 0, -12, 4, "fixture", 8, 24],
  ["inn_meals", "Prepared meals", "hearty_meal", 2, -12, 4, "fixture", 4, 12],
  [
    "stable_feed",
    "Barn hay and feed",
    "animal_feed",
    60,
    -27,
    24,
    "fixture",
    20,
    60,
  ],
  [
    "stable_water",
    "Animal trough water",
    "clean_water",
    80,
    38,
    23,
    "cart",
    30,
    120,
  ],
  [
    "stable_care",
    "Prepared stalls",
    "prepared_stall",
    0,
    38,
    21,
    "fixture",
    1,
    2,
  ],
  [
    "message_log",
    "Delivered notices",
    "delivered_notice",
    0,
    21,
    10,
    "sign",
    1,
    1,
  ],
  [
    "lumber_camp_logs",
    "Stacked rough timber",
    "timber_log",
    0,
    -22,
    18,
    "fixture",
    90,
    270,
  ],
  [
    "lumber_yard_lumber",
    "Seasoned building lumber",
    "building_lumber",
    0,
    -23,
    18,
    "fixture",
    90,
    4000,
  ],
  [
    "lumber_yard_project",
    "Lumber yard construction",
    "lumber_yard_facility",
    0,
    -22,
    18,
    "fixture",
    1,
    1,
  ],
  [
    "farmstead_project",
    "Farmstead construction",
    "farmstead",
    0,
    -26,
    24,
    "fixture",
    1,
    1,
  ],
  ["farm_seed", "Seed reserve", "seed_grain", 6, -26, 24, "fixture", 3, 12],
  ["farm_grain", "Stored grain", "grain", 0, -27, 24, "fixture", 16, 48],
  ["mill_flour", "Sacks of flour", "flour", 0, -26, 24, "fixture", 12, 30],
  [
    "farm_vegetables",
    "Root vegetables",
    "vegetables",
    0,
    -25,
    24,
    "fixture",
    6,
    36,
  ],
  ["dairy_milk", "Fresh milk", "milk", 0, -19, 24, "fixture", 6, 12],
  ["pasture_meat", "Butchered meat", "meat", 0, -21, 24, "fixture", 4, 12],
  ["farm_eggs", "Fresh eggs", "egg", 0, -27, 24, "fixture", 6, 18],
  ["sheep_wool", "Clean fleece", "wool", 0, -27, 24, "fixture", 4, 12],
  ["farm_manure", "Composted manure", "manure", 0, -27, 24, "fixture", 8, 24],
  [
    "quarry_stone",
    "Quarried building stone",
    "stone",
    0,
    24,
    30,
    "fixture",
    12,
    36,
  ],
  ["mine_iron_ore", "Iron ore", "iron_ore", 0, 25, 30, "fixture", 6, 18],
  ["mine_copper_ore", "Copper ore", "copper_ore", 0, 26, 30, "fixture", 4, 12],
  ["mine_tin_ore", "Tin ore", "tin_ore", 0, 27, 30, "fixture", 3, 9],
  ["forge_iron", "Iron ingots", "iron_ingot", 0, 11, 3, "forge", 4, 12],
  ["forge_steel", "Steel ingots", "steel_ingot", 0, 11, 3, "forge", 3, 8],
  ["forge_copper", "Copper ingots", "copper_ingot", 0, 11, 3, "forge", 2, 8],
  ["forge_tin", "Tin ingots", "tin_ingot", 0, 11, 3, "forge", 2, 6],
  ["forge_brass", "Brass ingots", "brass_ingot", 0, 11, 3, "forge", 2, 6],
  [
    "wild_forage",
    "Emergency forage basket",
    "wild_forage",
    0,
    -15,
    19,
    "fixture",
    4,
    8,
  ],
  [
    "housing_project",
    "Completed founder homes",
    "residence",
    0,
    -22,
    18,
    "fixture",
    3,
    3,
  ],
  ["founding_axes", "Woodcutting axes", "hand_axe", 3, -16, 18, "fixture"],
  ["founding_saws", "Crosscut saws", "crosscut_saw", 2, -16, 18, "fixture"],
  ["founding_pickaxes", "Quarry pickaxes", "pickaxe", 2, -16, 18, "fixture"],
  [
    "founding_hammers",
    "Building hammers",
    "claw_hammer",
    2,
    -16,
    18,
    "fixture",
  ],
];

const FOUNDING_STOCKPILE_KEYS = new Set([
  "inn_meals",
  "lumber_camp_logs",
  "lumber_yard_lumber",
  "lumber_yard_project",
  "farmstead_project",
  "housing_project",
  "farm_seed",
  "farm_grain",
  "mill_flour",
  "farm_vegetables",
  "dairy_milk",
  "pasture_meat",
  "farm_eggs",
  "sheep_wool",
  "farm_manure",
  "quarry_stone",
  "forge_iron",
  "forge_steel",
  "forge_copper",
  "forge_tin",
  "forge_brass",
  "hunting_bows",
  "netting_fiber",
  "fishing_nets",
  "wild_forage",
  "river_catch",
  "inn_fish",
  "founding_axes",
  "founding_saws",
  "founding_pickaxes",
  "founding_hammers",
  "stable_feed",
  "stable_water",
]);

const STARTING_SHOP_STOCK = {
  smithy: [
    "iron_mace",
    "longsword",
    "battleaxe",
    "warhammer",
    "hand_axe",
    "field_shovel",
    "shortbow",
  ],
  armorer: ["mage_robes", "chain_shirt", "scale_mail"],
};

const SHOP_COUNTERS = {
  smithy: { x: 3, y: 3 },
  apothecary: { x: 27, y: 3 },
  armorer: { x: 24, y: 16 },
};

function stockpileDefinition(values) {
  const [
    key,
    name,
    itemKind,
    quantity,
    x,
    y,
    containerKind,
    threshold,
    capacity,
    shopKey,
  ] = values;
  return {
    key,
    name,
    itemKind,
    quantity,
    position: { x, y },
    containerKind,
    threshold: threshold ?? 0,
    capacity: capacity ?? Math.max(quantity, 6),
    shopKey: shopKey ?? null,
  };
}

function startingShopDefinitions() {
  return Object.entries(STARTING_SHOP_STOCK).flatMap(([shopKey, goods]) =>
    goods.map((itemKind) => {
      const position = SHOP_COUNTERS[shopKey];
      return {
        key: `${shopKey}_${itemKind}`,
        name: `${itemKind.replaceAll("_", " ")} stock`,
        itemKind,
        quantity: 1,
        position: { ...position },
        containerKind: "counter",
        threshold: 0,
        capacity: 4,
        shopKey,
      };
    }),
  );
}

export const VILLAGE_STOCKPILE_DEFINITIONS = Object.freeze([
  ...BASE_STOCKPILES.map(stockpileDefinition),
  ...startingShopDefinitions(),
]);

export const RESIDENT_JOB_TEMPLATES = Object.freeze([
  {
    jobType: "mill_grain",
    name: "Mill grain into flour",
    personKey: "farmer",
    capability: "mill",
    skill: "milling",
    priority: 66,
    targetPosition: { x: -26, y: 24 },
    inputKey: "farm_grain",
    inputQuantity: 2,
    inputMinRemaining: 8,
    outputKey: "mill_flour",
    outputQuantity: 3,
    duration: 3,
    requiredFacility: "mill",
  },
  {
    jobType: "craft_weapon",
    name: "Forge ash spear",
    personKey: "smith",
    capability: "forge",
    priority: 60,
    targetPosition: { x: 11, y: 3 },
    inputKey: "smithy_supplies",
    outputKey: "smithy_weapons",
    duration: 3,
  },
  {
    jobType: "craft_hunting_bow",
    name: "Forge a hunting bow",
    personKey: "smith",
    capability: "forge",
    skill: "metalworking",
    priority: 122,
    targetPosition: { x: 11, y: 3 },
    requirements: [
      { key: "smithy_supplies", quantity: 1, consume: true },
      { key: "lumber_yard_lumber", quantity: 1, consume: true },
    ],
    outputKey: "hunting_bows",
    outputQuantity: 1,
    duration: 4,
    requiredFacility: "forge",
  },
  {
    jobType: "craft_fishing_net",
    name: "Knot a river fishing net",
    personKey: "fisher",
    capability: "fish",
    skill: "fishing",
    priority: 124,
    targetPosition: { x: 24, y: 59 },
    inputKey: "netting_fiber",
    inputQuantity: 2,
    outputKey: "fishing_nets",
    outputQuantity: 1,
    duration: 3,
    requiredFacility: "fishing_hut",
  },
  {
    jobType: "brew_remedy",
    name: "Brew healing potion",
    personKey: "herbalist",
    capability: "brew",
    priority: 70,
    targetPosition: { x: 29, y: 7 },
    inputKey: "apothecary_herbs",
    outputKey: "apothecary_remedies",
    duration: 2,
  },
  {
    jobType: "craft_armor",
    name: "Fit reinforced shield",
    personKey: "armorer",
    capability: "armorcraft",
    priority: 60,
    targetPosition: { x: 26, y: 20 },
    inputKey: "armorer_materials",
    outputKey: "armorer_shields",
    duration: 3,
  },
  {
    jobType: "prepare_meal",
    name: "Prepare fish stew",
    personKey: "innkeeper",
    capability: "cook",
    skill: "cooking",
    priority: 55,
    targetPosition: { x: -12, y: 4 },
    inputKey: "inn_fish",
    outputKey: "inn_meals",
    duration: 2,
  },
  {
    jobType: "bake_grain_meal",
    name: "Bake grain loaves",
    personKey: "innkeeper",
    capability: "cook",
    skill: "cooking",
    priority: 58,
    targetPosition: { x: -12, y: 4 },
    inputKey: "farm_grain",
    outputKey: "inn_meals",
    outputQuantity: 2,
    duration: 2,
  },
  {
    jobType: "cook_vegetable_stew",
    name: "Cook vegetable stew",
    personKey: "innkeeper",
    capability: "cook",
    skill: "cooking",
    priority: 57,
    targetPosition: { x: -12, y: 4 },
    inputKey: "farm_vegetables",
    outputKey: "inn_meals",
    duration: 2,
  },
  {
    jobType: "cook_beef_stew",
    name: "Cook beef stew",
    personKey: "innkeeper",
    capability: "cook",
    skill: "cooking",
    priority: 59,
    targetPosition: { x: -12, y: 4 },
    inputKey: "pasture_meat",
    outputKey: "inn_meals",
    outputQuantity: 2,
    duration: 2,
  },
  {
    jobType: "cook_egg_meal",
    name: "Cook eggs at the village hearth",
    personKey: "innkeeper",
    capability: "cook",
    skill: "cooking",
    priority: 56,
    targetPosition: { x: -12, y: 4 },
    inputKey: "farm_eggs",
    inputQuantity: 2,
    outputKey: "inn_meals",
    outputQuantity: 2,
    duration: 2,
  },
  {
    jobType: "catch_fish",
    name: "Fish the river",
    personKey: "fisher",
    capability: "fish",
    skill: "fishing",
    priority: 45,
    targetPosition: { x: -1, y: 16 },
    outputKey: "river_catch",
    duration: 2,
  },
  {
    jobType: "haul_stock",
    name: "Carry fish to the inn",
    personKey: "porter",
    capability: "haul",
    skill: "logistics",
    priority: 50,
    sourceKey: "river_catch",
    outputKey: "inn_fish",
    accessPosition: { x: -8, y: 10 },
    duration: 2,
  },
  {
    jobType: "tend_stable",
    name: "Prepare the horse stalls",
    personKey: "hostler",
    capability: "stablecare",
    priority: 65,
    targetPosition: { x: 38, y: 21 },
    inputKey: "stable_feed",
    outputKey: "stable_care",
    duration: 2,
  },
  {
    jobType: "deliver_message",
    name: "Post the town notices",
    personKey: "child",
    capability: "message",
    priority: 30,
    targetPosition: { x: 7, y: 10 },
    outputKey: "message_log",
    duration: 1,
  },
]);

export const SHOP_PROPRIETORS = Object.freeze({
  smithy: "smith",
  apothecary: "herbalist",
  armorer: "armorer",
});

export function createVillageStockpiles(runId) {
  return VILLAGE_STOCKPILE_DEFINITIONS.map((definition) => ({
    id: namedUuid(runId, `stockpile:${definition.key}`),
    definitionId: definitionId("stockpile", definition.key),
    entityType: "stockpile",
    ...structuredClone(definition),
    containerId: namedUuid(
      runId,
      `village-object:${definition.containerKind}:${definition.position.x},${definition.position.y}`,
    ),
  }));
}

export function createFoundingStockpiles(runId) {
  return createVillageStockpiles(runId)
    .filter((stockpile) => FOUNDING_STOCKPILE_KEYS.has(stockpile.key))
    .map((stockpile) => {
      if (["inn_meals", "inn_fish"].includes(stockpile.key)) {
        const position =
          stockpile.key === "inn_meals" ? { x: -14, y: 18 } : { x: -15, y: 19 };
        return {
          ...stockpile,
          quantity: stockpile.key === "inn_meals" ? 30 : stockpile.quantity,
          ...(stockpile.key === "inn_meals"
            ? { threshold: 40, capacity: 60 }
            : {}),
          position,
          containerId: namedUuid(
            runId,
            `village-object:${stockpile.containerKind}:${position.x},${position.y}`,
          ),
        };
      }
      return stockpile;
    });
}

export function stockpileByKey(state, key) {
  return state.village.stockpiles.find((stockpile) => stockpile.key === key);
}

export function shopStock(state, shopKey, itemKind) {
  return state.village.stockpiles.find(
    (stockpile) =>
      stockpile.shopKey === shopKey && stockpile.itemKind === itemKind,
  );
}
